from numpy import *
a=array([1,2,3],int)
print(a)
a=array([1.1,2.2,3.3],float)
print(a)
a=array(['a','b','c'])
print(a)
a=array(['vidya','faldu','manishbai'],dtype=str)
print(a)
a=linspace(0,10,5)
print(a)
a=logspace(1,4,5)
print(a)
a=arange(1,10,3)
print(a)
a=arange(10)
print(a)
a=arange(5,10)
print(a)
a=zeros(5)
print(a)
a=zeros(5,int)
print(a)
a=zeros(5,float)
print(a)
a=ones(5,int)
print(a)

#attribute of arrays

b=array([1,2,3,4,5])
print(b.ndim)
print(b.shape)
print(b.size)
print(b.itemsize)
print(b.dtype)
print(b.nbytes)

a=array([1,2,3])
a=ones((3,4),float)
print(a)
b=zeros((3,4),int)
print(b)
#dimension array
a=array([1,2,3])
print("1 dimension array")
print(a)
b=array([[1,1,1],[2,2,2]])
print("2 dimension array")
print(b)
c=array([
    [[3,3,3],[4,4,4]]
    ,[[5,5,5],[6,6,6]]
    ])
print("3 dimension array")
print(c)
